/* empty css                      */import{a as v,S as P,i as c}from"./assets/vendor-BkC4bTqC.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();async function u(r,t=1){return(await v.get("https://pixabay.com/api/",{params:{key:"55119464-7e56b6e0115e09eda171fae18",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t}})).data}const m=document.querySelector(".gallery"),f=document.querySelector(".loader"),g=document.querySelector(".load-more"),q=new P(".gallery a",{captionsData:"alt",captionDelay:250});function y(r){const t=r.map(({webformatURL:a,largeImageURL:s,tags:e,likes:o,views:n,comments:S,downloads:w})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${s}">
        <img class="gallery-image" src="${a}" alt="${e}" />
      </a>
      <div class="info">
        <p><b>Likes:</b> ${o}</p>
        <p><b>Views:</b> ${n}</p>
        <p><b>Comments:</b> ${S}</p>
        <p><b>Downloads:</b> ${w}</p>
      </div>
    </li>`).join("");m.insertAdjacentHTML("beforeend",t),q.refresh()}function M(){m.innerHTML=""}function p(){f.classList.remove("hidden")}function h(){f.classList.add("hidden")}function E(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const $=document.querySelector(".form"),x=document.querySelector(".load-more");let l="",i=1,L=0;$.addEventListener("submit",async r=>{if(r.preventDefault(),l=r.currentTarget.elements["search-text"].value.trim(),!l){c.warning({title:"Warning",message:"Please enter a search text!"});return}i=1,M(),d(),p();try{const t=await u(l,i);L=t.totalHits,t.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(t.hits),b())}catch(t){c.error({title:"Error",message:"Somsing wrong, please try again."}),console.log(t)}finally{h(),r.target.reset()}});x.addEventListener("click",async()=>{i+=1,d(),p();try{const r=await u(l,i);y(r.hits),b();const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}}catch(r){console.log(r)}finally{h()}});function b(){const r=Math.ceil(L/15);i>=r?(d(),c.info({message:"We're sorry, but you've reached the and of search results."})):E()}
//# sourceMappingURL=index.js.map
